"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";

import { getProjects } from "../../../../lib/projectStore";
import { priceEstimate, type MaterialLine } from "../../../../lib/pricing/priceEngine";

type Draft = {
  savedAt: string;
  jobDescription?: string;
  estimate?: GeneratedEstimate;
  laborRate?: number;
  markupPct?: number;
};

type UIState = {
  isSaved: boolean;
  lastSavedAt?: string;
};

type EstimateLineItem = {
  id: string;
  name: string;
  qty: number;
  unit: string;
  notes?: string;
  confidence?: "high" | "medium" | "low";
};

type GeneratedEstimate = {
  generatedAt: string;
  summary: string;
  assumptions: string[];
  lineItems: EstimateLineItem[];
  materials: MaterialLine[];
  laborHours: number;
};

function uid() {
  return Math.random().toString(36).slice(2, 10);
}

function shortScope(text: string, max = 120) {
  if (!text) return "";

  const cleaned = text
    .replace(/generated by ai.*$/i, "")
    .replace(/ai[- ]?generated.*$/i, "")
    .replace(/\s+/g, " ")
    .trim();

  if (cleaned.length <= max) return cleaned;
  return cleaned.slice(0, max).replace(/\s+\S*$/, "") + "...";
}

function autoTitle(scope: string) {
  const s = scope.toLowerCase();

  if (s.includes("water heater")) return "Water Heater Circuit Repair";
  if (s.includes("ev") || s.includes("charger")) return "EV Charger Installation";
  if (s.includes("panel") || s.includes("service")) return "Electrical Panel Work";
  if (s.includes("receptacle") || s.includes("outlet")) return "Outlet Installation";
  if (s.includes("light") || s.includes("fixture")) return "Lighting Installation";
  if (s.includes("generator")) return "Generator Electrical Work";

  return "Electrical Scope of Work";
}

function clampQty(n: number) {
  if (!Number.isFinite(n) || n <= 0) return 1;
  return Math.min(9999, Math.round(n));
}

function generateEstimateFromText(raw: string): GeneratedEstimate {
  const text = raw.trim();
  const lower = text.toLowerCase();

  const lineItems: EstimateLineItem[] = [];
  const assumptions: string[] = [];
  const materials: MaterialLine[] = [];
  let laborHours = 2;

  const add = (item: Omit<EstimateLineItem, "id">) => {
    lineItems.push({ id: uid(), ...item });
  };

  const addMaterial = (item: MaterialLine) => {
    materials.push(item);
  };

  const hasEV = /\bev\b|\be-v\b|charger|chargepoint|tesla|wall connector/.test(lower);
  const ftMatch = lower.match(/(\d{1,4})\s*(ft|feet|foot|')/);
  const runFt = ftMatch ? clampQty(parseInt(ftMatch[1], 10)) : undefined;

  if (hasEV) {
    laborHours = 4;

    add({
      name: "EV charger circuit",
      qty: 1,
      unit: "ea",
      notes: runFt != null ? `Approx. ${runFt} ft run.` : "Run length not specified.",
      confidence: runFt != null ? "medium" : "low",
    });

    const ampsMatch = lower.match(/(\d{2,3})\s*a\b/);
    const amps = ampsMatch ? parseInt(ampsMatch[1], 10) : 50;

    add({
      name: "2-pole breaker",
      qty: 1,
      unit: "ea",
      notes: `${amps}A assumed/detected.`,
      confidence: ampsMatch ? "medium" : "low",
    });

    addMaterial({
      skuKey: amps >= 60 ? "breaker_2p_60a" : "breaker_2p_50a",
      qty: 1,
      unit: "ea",
      name: `${amps >= 60 ? "60A" : "50A"} 2-Pole Breaker`,
    });

    const has1450 = /14-?50|nema\s*14\s*-?\s*50|50\s*a\s*receptacle/.test(lower);
    const hardwired = /hardwire|hard-wired|wall\s*connector/.test(lower);

    if (has1450 && !hardwired) {
      add({
        name: "14-50 receptacle",
        qty: 1,
        unit: "ea",
        confidence: "medium",
      });

      addMaterial({
        skuKey: "receptacle_nema_14_50",
        qty: 1,
        unit: "ea",
        name: "NEMA 14-50 Receptacle",
      });

      addMaterial({
        skuKey: "box_4_square",
        qty: 1,
        unit: "ea",
        name: "4\" Square Box",
      });

      addMaterial({
        skuKey: "cover_raised_14_50",
        qty: 1,
        unit: "ea",
        name: "Raised Receptacle Cover",
      });
    } else if (hardwired) {
      add({
        name: "Hardwire termination",
        qty: 1,
        unit: "ea",
        confidence: "medium",
      });

      addMaterial({
        skuKey: "hardwire_kit",
        qty: 1,
        unit: "ea",
        name: "Hardwire Kit",
      });
    } else {
      add({
        name: "EV termination hardware",
        qty: 1,
        unit: "ea",
        notes: "Exact termination type not specified.",
        confidence: "low",
      });

      assumptions.push("Termination type not specified; used placeholder hardware allowance.");

      addMaterial({
        skuKey: "ev_termination_misc",
        qty: 1,
        unit: "lot",
        name: "EV Termination Hardware",
      });
    }

    if (runFt != null) {
      add({
        name: "Cable / conduit run",
        qty: runFt,
        unit: "ft",
        confidence: "medium",
      });

      addMaterial({
        skuKey: "wire_copper_6awg",
        qty: runFt,
        unit: "ft",
        name: "#6 Copper Wire",
      });

      addMaterial({
        skuKey: "conduit_emt_1in",
        qty: Math.max(10, Math.ceil(runFt * 0.6)),
        unit: "ft",
        name: "1\" EMT Conduit",
      });

      addMaterial({
        skuKey: "fittings_emt_misc",
        qty: 1,
        unit: "lot",
        name: "EMT Fittings",
      });
    } else {
      addMaterial({
        skuKey: "wire_branch_circuit_misc",
        qty: 1,
        unit: "lot",
        name: "Branch Circuit Wire",
      });

      addMaterial({
        skuKey: "fittings_emt_misc",
        qty: 1,
        unit: "lot",
        name: "Raceway / Fittings",
      });
    }

    if (/attic/.test(lower)) assumptions.push("Attic access assumed available.");
    if (/crawl/.test(lower)) assumptions.push("Crawlspace access assumed available.");
    if (/garage/.test(lower)) assumptions.push("Work area assumed in/near garage.");
  }

  const lightMatch = lower.match(/(\d{1,3})\s*(?:new\s*)?(light|lights|fixture|fixtures)\b/);
  if (lightMatch) {
    const qty = clampQty(parseInt(lightMatch[1], 10));
    add({ name: "Install light fixture(s)", qty, unit: "ea", confidence: "medium" });
    laborHours += qty;
    addMaterial({
      skuKey: "light_fixture_allowance",
      qty,
      unit: "ea",
      name: "Light Fixture Allowance",
    });
  } else if (/\blight(s)?\b|\bfixture(s)?\b/.test(lower)) {
    add({
      name: "Install light fixture(s)",
      qty: 1,
      unit: "ea",
      notes: "Quantity not specified.",
      confidence: "low",
    });
    assumptions.push("Lighting quantity not specified; assumed 1.");
    laborHours += 1;
    addMaterial({
      skuKey: "light_fixture_allowance",
      qty: 1,
      unit: "ea",
      name: "Light Fixture Allowance",
    });
  }

  const recepMatch = lower.match(/(\d{1,3})\s*(receptacle|receptacles|outlet|outlets)\b/);
  if (recepMatch) {
    const qty = clampQty(parseInt(recepMatch[1], 10));
    add({ name: "Install receptacle(s)", qty, unit: "ea", confidence: "medium" });
    laborHours += Math.max(1, qty * 0.5);

    addMaterial({
      skuKey: "receptacle_duplex_20a",
      qty,
      unit: "ea",
      name: "20A Duplex Receptacle",
    });

    addMaterial({
      skuKey: "cover_decora_or_duplex",
      qty,
      unit: "ea",
      name: "Device Cover Plate",
    });
  }

  if (/panel\s*upgrade|service\s*upgrade/.test(lower)) {
    add({
      name: "Electrical panel / service upgrade",
      qty: 1,
      unit: "ea",
      notes: "Exact amperage and scope TBD.",
      confidence: "low",
    });
    assumptions.push("Panel/service upgrade details TBD.");
    laborHours += 8;

    addMaterial({
      skuKey: "panel_upgrade_allowance",
      qty: 1,
      unit: "ea",
      name: "Panel Upgrade Allowance",
    });
  }

  if (lineItems.length === 0 && text.length > 0) {
    add({
      name: "General electrical scope",
      qty: 1,
      unit: "lot",
      notes: "Description needs more detail.",
      confidence: "low",
    });

    assumptions.push("Description too vague for detailed automatic takeoff.");
    laborHours = 2;

    addMaterial({
      skuKey: "misc_consumables",
      qty: 1,
      unit: "lot",
      name: "Misc Fittings / Consumables",
    });
  }

  if (materials.length === 0) {
    addMaterial({
      skuKey: "misc_consumables",
      qty: 1,
      unit: "lot",
      name: "Misc Fittings / Consumables",
    });
  }

  const summary =
    hasEV && text.length > 0
      ? "Detected EV charging-related scope and generated a starter estimate."
      : "Generated a starter estimate from the job description.";

  return {
    generatedAt: new Date().toISOString(),
    summary,
    assumptions,
    lineItems,
    materials,
    laborHours,
  };
}

export default function NewEstimatePage() {
  const params = useParams<{ id: string }>();
  const projectId = params?.id;

  const project = getProjects().find((p) => p.id === projectId);
  const draftKey = `voltscope:draft-estimate:${projectId ?? "unknown"}`;

  const [uiState, setUiState] = useState<UIState>({ isSaved: false, lastSavedAt: undefined });
  const [jobDescription, setJobDescription] = useState("");
  const [estimate, setEstimate] = useState<GeneratedEstimate | null>(null);

  const [markupPct, setMarkupPct] = useState(20);
  const [laborRate, setLaborRate] = useState(150);
  const [priced, setPriced] = useState<ReturnType<typeof priceEstimate> | null>(null);
  const [showAllMaterials, setShowAllMaterials] = useState(false);

  const [genState, setGenState] = useState<{
    status: "idle" | "loading" | "ready" | "error";
    msg?: string;
  }>({ status: "idle" });

  const [progress, setProgress] = useState(0);

  useEffect(() => {
    if (!projectId) return;

    const raw = localStorage.getItem(draftKey);
    if (!raw) return;

    try {
      const saved = JSON.parse(raw) as Partial<Draft>;

      if (typeof saved.jobDescription === "string") setJobDescription(saved.jobDescription);
      if (typeof saved.laborRate === "number" && Number.isFinite(saved.laborRate)) setLaborRate(saved.laborRate);
      if (typeof saved.markupPct === "number" && Number.isFinite(saved.markupPct)) setMarkupPct(saved.markupPct);

      if (saved.estimate && typeof saved.estimate === "object") {
        setEstimate(saved.estimate as GeneratedEstimate);
        setGenState({ status: "ready" });
      }

      if (saved.savedAt) setUiState({ isSaved: true, lastSavedAt: saved.savedAt });
    } catch {
      // ignore bad draft
    }
  }, [projectId, draftKey]);

  useEffect(() => {
    if (!estimate) {
      setPriced(null);
      return;
    }

    const next = priceEstimate({
      month: "2026-03",
      state: "NC",
      laborRate,
      markupPct,
      laborHours: estimate.laborHours,
      materials: estimate.materials,
    });

    setPriced(next);
  }, [estimate, laborRate, markupPct]);

  useEffect(() => {
    if (genState.status !== "loading") {
      setProgress(0);
      return;
    }

    setProgress(8);

    const id = window.setInterval(() => {
      setProgress((p) => {
        const next = p + Math.max(1, Math.round((92 - p) * 0.12));
        return Math.min(92, next);
      });
    }, 250);

    return () => window.clearInterval(id);
  }, [genState.status]);

  function saveDraft() {
    if (!projectId) return;

    const payload: Draft = {
      savedAt: new Date().toISOString(),
      jobDescription: jobDescription.trim(),
      estimate: estimate ?? undefined,
      laborRate,
      markupPct,
    };

    localStorage.setItem(draftKey, JSON.stringify(payload));
    setUiState({ isSaved: true, lastSavedAt: payload.savedAt });
  }

  async function handleGenerate() {
    const text = jobDescription.trim();

    if (!text) {
      setGenState({ status: "error", msg: "Please enter a job description first." });
      return;
    }

    setGenState({ status: "loading" });

    const fallback = generateEstimateFromText(text);
    const controller = new AbortController();
    const timeoutId = window.setTimeout(() => controller.abort(), 26000);

    try {
      const r = await fetch("/api/estimate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ description: text }),
        signal: controller.signal,
      });

      const raw = await r.text();

      let data: any;
      try {
        data = JSON.parse(raw);
      } catch {
        data = null;
      }

      if (!r.ok || !data) {
        setEstimate(fallback);
        setProgress(100);
        setGenState({
          status: "ready",
          msg: !r.ok ? `API failed, used local estimate fallback.` : "API returned invalid data, used local fallback.",
        });

        if (projectId) {
          const payload: Draft = {
            savedAt: new Date().toISOString(),
            jobDescription: text,
            estimate: fallback,
            laborRate,
            markupPct,
          };
          localStorage.setItem(draftKey, JSON.stringify(payload));
          setUiState({ isSaved: true, lastSavedAt: payload.savedAt });
        }
        return;
      }

      const apiMaterials = Array.isArray(data?.materials) ? data.materials : [];
      const apiLineItems = Array.isArray(data?.lineItems) ? data.lineItems : [];
      const apiAssumptions = Array.isArray(data?.assumptions) ? data.assumptions : [];

      const generated: GeneratedEstimate = {
        generatedAt: new Date().toISOString(),
        summary: data?.summary ?? fallback.summary,
        assumptions: apiAssumptions.length ? apiAssumptions : fallback.assumptions,
        lineItems:
          apiLineItems.length > 0
            ? apiLineItems.map((item: any) => ({
                id: uid(),
                name: item?.name ?? "Scope Item",
                qty: typeof item?.qty === "number" ? item.qty : 1,
                unit: item?.unit ?? "ea",
                notes: typeof item?.notes === "string" ? item.notes : undefined,
                confidence:
                  item?.confidence === "high" || item?.confidence === "medium" || item?.confidence === "low"
                    ? item.confidence
                    : "medium",
              }))
            : fallback.lineItems,
        materials: apiMaterials.length > 0 ? apiMaterials : fallback.materials,
        laborHours: typeof data?.laborHours === "number" && data.laborHours > 0 ? data.laborHours : fallback.laborHours,
      };

      setEstimate(generated);
      setProgress(100);
      setGenState({ status: "ready" });

      if (projectId) {
        const payload: Draft = {
          savedAt: new Date().toISOString(),
          jobDescription: text,
          estimate: generated,
          laborRate,
          markupPct,
        };
        localStorage.setItem(draftKey, JSON.stringify(payload));
        setUiState({ isSaved: true, lastSavedAt: payload.savedAt });
      }
    } catch (e: any) {
      const msg =
        e?.name === "AbortError"
          ? "Request timed out. Used local estimate fallback."
          : "Request failed. Used local estimate fallback.";

      setEstimate(fallback);
      setProgress(100);
      setGenState({ status: "ready", msg });

      if (projectId) {
        const payload: Draft = {
          savedAt: new Date().toISOString(),
          jobDescription: text,
          estimate: fallback,
          laborRate,
          markupPct,
        };
        localStorage.setItem(draftKey, JSON.stringify(payload));
        setUiState({ isSaved: true, lastSavedAt: payload.savedAt });
      }
    } finally {
      window.clearTimeout(timeoutId);
    }
  }

  function clearEstimate() {
    setJobDescription("");
    setEstimate(null);
    setPriced(null);
    setProgress(0);
    setGenState({ status: "idle" });
    setShowAllMaterials(false);

    if (projectId) {
      localStorage.removeItem(draftKey);
      setUiState({ isSaved: false, lastSavedAt: undefined });
    }
  }

  const C = {
    teal: "#00778B",
    tealDark: "#005F70",
    tealLight: "#E0F4F7",
    gold: "#C8A96E",
    goldLight: "#F5ECD8",
    navy: "#003057",
    navyMid: "#04406B",
    white: "#FFFFFF",
    offWhite: "#F7FAFC",
    ink: "#0A1F33",
    muted: "rgba(0, 48, 87, 0.52)",
    divider: "rgba(0, 119, 139, 0.14)",
  } as const;

  const shadows = {
    card: "0 4px 24px rgba(0, 48, 87, 0.09), 0 1px 4px rgba(0, 48, 87, 0.06)",
    raised: "0 8px 32px rgba(0, 48, 87, 0.12), 0 2px 8px rgba(0, 48, 87, 0.07)",
    teal: "0 4px 20px rgba(0, 119, 139, 0.22)",
  } as const;

  const radius = { sm: 10, md: 14, lg: 18 } as const;

  const font = {
    display: "'Barlow Condensed', 'Arial Narrow', Arial, sans-serif",
    body: "'DM Sans', 'Segoe UI', system-ui, sans-serif",
    mono: "'DM Mono', 'Fira Code', monospace",
  } as const;

  const panelStyle: CSSProperties = {
    background: C.white,
    border: `1px solid ${C.divider}`,
    borderRadius: radius.lg,
    boxShadow: shadows.card,
    padding: 18,
    fontFamily: font.body,
  };

  const btnPrimary: CSSProperties = {
    padding: "10px 20px",
    borderRadius: radius.sm,
    border: `1.5px solid ${C.tealDark}`,
    background: `linear-gradient(160deg, ${C.teal} 0%, ${C.tealDark} 100%)`,
    color: C.white,
    fontFamily: font.display,
    fontWeight: 700,
    fontSize: 14,
    letterSpacing: 0.6,
    cursor: "pointer",
    boxShadow: shadows.teal,
    whiteSpace: "nowrap",
  };

  const btnSecondary: CSSProperties = {
    padding: "10px 14px",
    borderRadius: radius.sm,
    border: `1px solid rgba(0, 119, 139, 0.26)`,
    background: `linear-gradient(180deg, ${C.white} 0%, #F6FBFC 100%)`,
    color: C.navy,
    fontFamily: font.display,
    fontWeight: 800,
    fontSize: 13,
    letterSpacing: 0.55,
    cursor: "pointer",
    boxShadow: "0 6px 18px rgba(0, 48, 87, 0.08)",
    whiteSpace: "nowrap",
  };

  const inputStyle: CSSProperties = {
    width: "100%",
    padding: "12px 12px",
    borderRadius: radius.md,
    border: `1px solid rgba(0, 119, 139, 0.22)`,
    outline: "none",
    fontFamily: font.body,
    fontSize: 14,
    lineHeight: 1.4,
    color: C.ink,
    background: "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.7)",
  };

  const helperStyle: CSSProperties = {
    marginTop: 8,
    fontSize: 12,
    color: C.muted,
    fontFamily: font.body,
  };

  const miniInput: CSSProperties = {
    width: 120,
    padding: "8px 10px",
    borderRadius: radius.md,
    border: `1px solid rgba(0, 119, 139, 0.22)`,
    outline: "none",
    fontFamily: font.mono,
    fontSize: 13,
    color: C.ink,
    background: "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
  };

  const isLocked = genState.status === "loading" || genState.status === "ready";
  const canGenerate = useMemo(() => jobDescription.trim().length > 0 && !isLocked, [jobDescription, isLocked]);

  function conciseMaterialName(name: string, skuKey?: string) {
    const raw = `${name || ""} ${skuKey || ""}`.toLowerCase();

    if (raw.includes("misc_consumables") || raw.includes("consumables")) return "Misc. Fittings";
    if (raw.includes("breaker")) return "Breaker";
    if (raw.includes("nema 14-50")) return "14-50 Receptacle";
    if (raw.includes("receptacle")) return "Receptacle";
    if (raw.includes("hardwire")) return "Hardwire Kit";
    if (raw.includes("charger")) return "EV Charger";
    if (raw.includes("conduit")) return "Conduit";
    if (raw.includes("wire")) return "Wire";
    if (raw.includes("cable")) return "Cable";
    if (raw.includes("mc")) return "MC Cable";
    if (raw.includes("disconnect")) return "Disconnect";
    if (raw.includes("fitting")) return "Fittings";
    if (raw.includes("box")) return "Box";
    if (raw.includes("cover")) return "Cover";

    return name
      .replace(/\(.*?\)/g, "")
      .replace(/includes?.*$/i, "")
      .replace(/with.*$/i, "")
      .replace(/\s+/g, " ")
      .trim()
      .split(" ")
      .slice(0, 3)
      .join(" ");
  }

  const previewCount = 4;
  const materialRows = priced?.pricedMaterials ?? [];
  const visibleMaterials = showAllMaterials ? materialRows : materialRows.slice(0, previewCount);
  const hiddenMaterialCount = Math.max(0, materialRows.length - previewCount);

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700;800&family=DM+Sans:wght@400;500;600;700&family=DM+Mono:wght@400;500&display=swap');

        * { box-sizing: border-box; }
        body { margin: 0; background: ${C.offWhite}; }

        .page {
          min-height: 100vh;
          background: linear-gradient(160deg, #EAF4F7 0%, #F7FAFC 40%, #F0EBE1 100%);
          padding: 20px;
          font-family: ${font.body};
          color: ${C.ink};
        }

        .header-bar {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 14px;
          padding: 14px 20px;
          border-radius: ${radius.lg}px;
          background: linear-gradient(135deg, ${C.navy} 0%, ${C.navyMid} 100%);
          box-shadow: ${shadows.raised};
          flex-wrap: wrap;
        }

        .header-left {
          display: flex;
          align-items: center;
          gap: 12px;
          min-width: 260px;
        }

        .header-accent {
          width: 4px;
          height: 38px;
          border-radius: 4px;
          background: linear-gradient(180deg, ${C.gold} 0%, ${C.teal} 100%);
          flex-shrink: 0;
        }

        .back-link {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          text-decoration: none;
          color: rgba(255,255,255,0.75);
          font-weight: 600;
          font-size: 13px;
          padding: 7px 12px;
          border-radius: ${radius.sm}px;
          border: 1px solid rgba(255,255,255,0.15);
          background: rgba(255,255,255,0.08);
          transition: background 0.15s, color 0.15s;
          white-space: nowrap;
        }

        .back-link:hover {
          background: rgba(255,255,255,0.16);
          color: ${C.white};
        }

        .header-title {
          font-family: ${font.display};
          font-weight: 800;
          font-size: 22px;
          letter-spacing: 0.5px;
          color: ${C.white};
          line-height: 1.1;
        }

        .header-sub {
          font-size: 13px;
          color: rgba(255,255,255,0.55);
          margin-top: 2px;
          font-weight: 500;
        }

        .content {
          max-width: 1160px;
          margin: 0 auto;
        }

        .grid {
          display: grid;
          grid-template-columns: 1fr;
          gap: 14px;
          margin-top: 14px;
        }

        .panel-title {
          font-family: ${font.display};
          font-weight: 800;
          font-size: 16px;
          letter-spacing: 0.3px;
          color: ${C.navy};
          margin: 0;
        }

        .badge {
          display: inline-block;
          padding: 2px 9px;
          border-radius: 20px;
          font-family: ${font.display};
          font-weight: 700;
          font-size: 11px;
          letter-spacing: 0.8px;
          text-transform: uppercase;
          background: ${C.tealLight};
          color: ${C.tealDark};
          border: 1px solid rgba(0,119,139,0.20);
          white-space: nowrap;
        }

        .meta-row {
          margin-top: 6px;
          font-size: 13px;
          color: ${C.muted};
        }

        .meta-strong {
          font-weight: 700;
          color: ${C.teal};
        }

        .saved-row {
          margin-top: 10px;
          display: flex;
          gap: 10px;
          align-items: center;
          flex-wrap: wrap;
          color: rgba(255,255,255,0.70);
          font-size: 12px;
          font-family: ${font.mono};
        }

        @media (max-width: 720px) {
          .header-left { min-width: 0; }
        }
      `}</style>

      <div className="page">
        <div className="content">
          <div className="header-bar">
            <div className="header-left">
              <div className="header-accent" />
              <Link href={`/projects/${projectId}`} className="back-link">
                ← Back
              </Link>
              <div>
                <div className="header-title">New Estimate</div>
                <div className="header-sub">
                  {project?.customerName ?? "Unnamed Project"} &nbsp;·&nbsp; {project?.jobType ?? "Unknown"}
                </div>
                {uiState.isSaved && uiState.lastSavedAt && (
                  <div className="saved-row">Last saved: {new Date(uiState.lastSavedAt).toLocaleString()}</div>
                )}
              </div>
            </div>

            <button type="button" onClick={saveDraft} style={btnPrimary}>
              💾 Save Draft
            </button>
          </div>

          <div className="grid">
            <div style={panelStyle}>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  marginBottom: 12,
                  gap: 12,
                  flexWrap: "wrap",
                }}
              >
                <h2 className="panel-title">Project</h2>
                <span className="badge">Active</span>
              </div>

              <div
                style={{
                  fontFamily: font.display,
                  fontWeight: 800,
                  fontSize: 18,
                  color: C.navy,
                  letterSpacing: 0.2,
                }}
              >
                {project?.customerName ?? "Unnamed Project"}
              </div>

              <div className="meta-row">
                Job Type: <span className="meta-strong">{project?.jobType ?? "Unknown"}</span>
              </div>

              {projectId && <div className="meta-row">Project ID: {projectId}</div>}
            </div>

            <div style={panelStyle}>
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  marginBottom: 12,
                  gap: 12,
                  flexWrap: "wrap",
                }}
              >
                <h2 className="panel-title">Job Description</h2>
                <span className="badge">Input</span>
              </div>

              <textarea
                value={jobDescription}
                onChange={(e) => {
                  setJobDescription(e.target.value);
                  if (genState.status === "error") setGenState({ status: "idle" });
                }}
                placeholder="Describe the job scope... (example: Install EV charger in garage, 25ft run through attic, new 60A breaker, permit included)"
                rows={6}
                style={inputStyle}
              />

              <div
                style={{
                  display: "flex",
                  gap: 10,
                  alignItems: "center",
                  marginTop: 12,
                  flexWrap: "wrap",
                }}
              >
                <button
                  type="button"
                  onClick={handleGenerate}
                  style={{
                    ...btnSecondary,
                    opacity: canGenerate ? 1 : 0.55,
                    cursor: canGenerate ? "pointer" : "not-allowed",
                  }}
                  disabled={!canGenerate}
                  title={
                    genState.status === "loading"
                      ? "Generating…"
                      : genState.status === "ready"
                        ? "Estimate already generated. Clear to start a new one."
                        : !jobDescription.trim()
                          ? "Enter a job description to generate."
                          : "Generate estimate"
                  }
                >
                  ⚡ Generate Estimate
                </button>

                <button
                  type="button"
                  onClick={clearEstimate}
                  style={{
                    ...btnSecondary,
                    opacity: genState.status === "ready" ? 1 : 0.55,
                    cursor: genState.status === "ready" ? "pointer" : "not-allowed",
                  }}
                  disabled={genState.status !== "ready"}
                  title={genState.status !== "ready" ? "Generate an estimate first." : "Clear and start a new estimate."}
                >
                  🧹 Start New Estimate
                </button>

                {genState.status === "error" && (
                  <span
                    style={{
                      fontFamily: font.mono,
                      fontSize: 12,
                      color: "rgba(160, 24, 24, 0.85)",
                      background: "rgba(255, 235, 235, 0.8)",
                      border: "1px solid rgba(160, 24, 24, 0.18)",
                      padding: "6px 10px",
                      borderRadius: 999,
                    }}
                  >
                    {genState.msg}
                  </span>
                )}

                {genState.status === "loading" && (
                  <span
                    style={{
                      fontFamily: font.mono,
                      fontSize: 12,
                      color: "rgba(0,48,87,0.75)",
                      background: "rgba(224,244,247,0.9)",
                      border: "1px solid rgba(0,119,139,0.18)",
                      padding: "6px 10px",
                      borderRadius: 999,
                    }}
                  >
                    Generating…
                  </span>
                )}

                {genState.status === "loading" && (
                  <div
                    style={{
                      width: "100%",
                      maxWidth: 420,
                      height: 10,
                      borderRadius: 999,
                      overflow: "hidden",
                      border: "1px solid rgba(0,119,139,0.22)",
                      background: "rgba(0,48,87,0.06)",
                    }}
                    aria-label="Generating estimate progress"
                  >
                    <div
                      style={{
                        height: "100%",
                        width: `${progress}%`,
                        background: `linear-gradient(90deg, ${C.teal} 0%, ${C.tealDark} 100%)`,
                        transition: "width 180ms ease",
                      }}
                    />
                  </div>
                )}

                {estimate?.generatedAt && genState.status === "ready" && (
                  <span
                    style={{
                      fontFamily: font.mono,
                      fontSize: 12,
                      color: "rgba(255,255,255,0.85)",
                      background: "rgba(0, 48, 87, 0.25)",
                      border: "1px solid rgba(255,255,255,0.16)",
                      padding: "6px 10px",
                      borderRadius: 999,
                    }}
                  >
                    Generated: {new Date(estimate.generatedAt).toLocaleString()}
                  </span>
                )}

                {genState.msg && genState.status === "ready" && (
                  <span
                    style={{
                      fontFamily: font.mono,
                      fontSize: 12,
                      color: C.navy,
                      background: "rgba(224,244,247,0.9)",
                      border: "1px solid rgba(0,119,139,0.18)",
                      padding: "6px 10px",
                      borderRadius: 999,
                    }}
                  >
                    {genState.msg}
                  </span>
                )}
              </div>

              <div style={helperStyle}>
                Tip: Include distances, voltage/amps, number of devices, and any access details (attic/crawlspace,
                trenching, etc).
              </div>
            </div>

            {estimate && (
              <div
                style={{
                  ...panelStyle,
                  padding: 0,
                  overflow: "hidden",
                }}
              >
                <div
                  style={{
                    padding: "14px 18px",
                    background: `linear-gradient(135deg, ${C.tealLight} 0%, #F8FCFD 100%)`,
                    borderBottom: `1px solid ${C.divider}`,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    gap: 12,
                    flexWrap: "wrap",
                  }}
                >
                  <h2 className="panel-title" style={{ margin: 0 }}>
                    Scope Summary
                  </h2>
                  <span className="badge">Draft Scope</span>
                </div>

                <div style={{ padding: 18 }}>
                  <div
                    style={{
                      fontFamily: font.body,
                      fontSize: 14,
                      lineHeight: 1.5,
                      color: C.ink,
                      fontWeight: 600,
                    }}
                  >
                    <div
                      style={{
                        fontFamily: font.display,
                        fontSize: 18,
                        fontWeight: 800,
                        color: C.navy,
                        marginBottom: 6,
                      }}
                    >
                      {autoTitle(estimate.summary)}
                    </div>

                    <div
                      style={{
                        fontFamily: font.body,
                        fontSize: 14,
                        lineHeight: 1.5,
                        color: C.ink,
                        fontWeight: 600,
                      }}
                    >
                      {shortScope(estimate.summary)}
                    </div>
                  </div>

                  {estimate.assumptions.length > 0 && (
                    <div
                      style={{
                        marginTop: 12,
                        fontSize: 12,
                        color: C.muted,
                        lineHeight: 1.5,
                      }}
                    >
                      {estimate.assumptions.slice(0, 2).join(" · ")}
                    </div>
                  )}
                </div>
              </div>
            )}

            {priced && (
              <div style={panelStyle}>
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    marginBottom: 12,
                    gap: 12,
                    flexWrap: "wrap",
                  }}
                >
                  <h2 className="panel-title">Totals</h2>
                  <span className="badge">Pricing</span>
                </div>

                <div
                  style={{
                    marginBottom: 12,
                    border: `1px solid ${C.divider}`,
                    borderRadius: radius.md,
                    overflow: "hidden",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "space-between",
                      gap: 12,
                      background: `linear-gradient(180deg, ${C.tealLight} 0%, #F6FBFC 100%)`,
                      padding: "10px 12px",
                      borderBottom: `1px solid ${C.divider}`,
                      flexWrap: "wrap",
                    }}
                  >
                    <div>
                      <div
                        style={{
                          fontFamily: font.display,
                          fontWeight: 800,
                          color: C.navy,
                          letterSpacing: 0.4,
                          fontSize: 12,
                          textTransform: "uppercase",
                        }}
                      >
                        Material List
                      </div>

                      <div
                        style={{
                          marginTop: 3,
                          fontSize: 12,
                          color: C.muted,
                          fontFamily: font.mono,
                        }}
                      >
                        {materialRows.length} items · ${priced.materialTotal.toFixed(2)}
                      </div>
                    </div>

                    {materialRows.length > previewCount && (
                      <button
                        type="button"
                        onClick={() => setShowAllMaterials((s) => !s)}
                        style={{
                          ...btnSecondary,
                          padding: "6px 10px",
                          fontSize: 12,
                        }}
                      >
                        {showAllMaterials ? "Show Less" : `Show All (${materialRows.length})`}
                      </button>
                    )}
                  </div>

                  {visibleMaterials.map((m) => (
                    <div
                      key={m.skuKey}
                      style={{
                        display: "grid",
                        gridTemplateColumns: "1.3fr 0.35fr 0.6fr 0.6fr",
                        padding: "12px 14px",
                        borderTop: `1px solid ${C.divider}`,
                        alignItems: "center",
                        gap: 10,
                        background: m.missingFromPricebook
                          ? "linear-gradient(180deg, rgba(200,169,110,0.10) 0%, rgba(245,236,216,0.6) 100%)"
                          : "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
                      }}
                    >
                      <div style={{ minWidth: 0 }}>
                        <div style={{ fontWeight: 800, color: C.navy, fontSize: 14, lineHeight: 1.25 }}>
                          {conciseMaterialName(m.name, m.skuKey)}
                        </div>
                        <div style={{ marginTop: 4, fontSize: 12, color: C.muted, fontFamily: font.mono }}>
                          {m.skuKey}
                          {m.missingFromPricebook ? " · missing from price book" : ""}
                        </div>
                      </div>

                      <div style={{ textAlign: "right", fontFamily: font.mono, color: C.ink, fontSize: 13 }}>
                        {m.qty}
                      </div>

                      <div style={{ textAlign: "right", fontFamily: font.mono, color: C.muted, fontSize: 13 }}>
                        {m.unit} @ ${m.adjUnitCost.toFixed(2)}
                      </div>

                      <div style={{ textAlign: "right", fontFamily: font.mono, color: C.ink, fontSize: 13 }}>
                        ${m.lineTotal.toFixed(2)}
                      </div>
                    </div>
                  ))}

                  {!showAllMaterials && hiddenMaterialCount > 0 && (
                    <div
                      style={{
                        padding: "10px 12px",
                        borderTop: `1px solid ${C.divider}`,
                        background: "rgba(0,119,139,0.04)",
                        fontSize: 12,
                        color: C.muted,
                        fontFamily: font.body,
                      }}
                    >
                      Showing {visibleMaterials.length} of {materialRows.length} materials · {hiddenMaterialCount} more
                      hidden
                    </div>
                  )}
                </div>

                <div
                  style={{
                    display: "flex",
                    gap: 12,
                    alignItems: "center",
                    flexWrap: "wrap",
                    marginBottom: 12,
                  }}
                >
                  <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                    <span style={{ fontFamily: font.display, fontWeight: 800, color: C.navy }}>Labor Rate</span>
                    <input
                      style={miniInput}
                      inputMode="numeric"
                      value={laborRate}
                      onChange={(e) => {
                        const v = Number(e.target.value);
                        setLaborRate(Number.isFinite(v) ? v : 0);
                      }}
                      onBlur={saveDraft}
                    />
                    <span style={{ fontFamily: font.mono, color: C.muted, fontSize: 12 }}>/hr</span>
                  </div>

                  <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                    <span style={{ fontFamily: font.display, fontWeight: 800, color: C.navy }}>Markup</span>
                    <input
                      style={miniInput}
                      inputMode="numeric"
                      value={markupPct}
                      onChange={(e) => {
                        const v = Number(e.target.value);
                        setMarkupPct(Number.isFinite(v) ? v : 0);
                      }}
                      onBlur={saveDraft}
                    />
                    <span style={{ fontFamily: font.mono, color: C.muted, fontSize: 12 }}>%</span>
                  </div>

                  <button type="button" onClick={saveDraft} style={btnSecondary}>
                    💾 Save Pricing
                  </button>
                </div>

                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                  <div
                    style={{
                      padding: 12,
                      borderRadius: radius.md,
                      border: `1px solid ${C.divider}`,
                      background: "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
                    }}
                  >
                    <div style={{ fontFamily: font.display, fontWeight: 800, color: C.navy }}>Material Total</div>
                    <div style={{ fontFamily: font.mono, fontSize: 18, marginTop: 6 }}>
                      ${priced.materialTotal.toFixed(2)}
                    </div>
                  </div>

                  <div
                    style={{
                      padding: 12,
                      borderRadius: radius.md,
                      border: `1px solid ${C.divider}`,
                      background: "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
                    }}
                  >
                    <div style={{ fontFamily: font.display, fontWeight: 800, color: C.navy }}>Labor Total</div>
                    <div style={{ fontFamily: font.mono, fontSize: 18, marginTop: 6 }}>
                      ${priced.laborTotal.toFixed(2)}
                    </div>
                    <div style={{ marginTop: 6, fontSize: 12, color: C.muted, fontFamily: font.mono }}>
                      {estimate?.laborHours ?? 0} hrs @ ${laborRate}/hr
                    </div>
                  </div>

                  <div
                    style={{
                      padding: 12,
                      borderRadius: radius.md,
                      border: `1px solid ${C.divider}`,
                      background: "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
                    }}
                  >
                    <div style={{ fontFamily: font.display, fontWeight: 800, color: C.navy }}>Subtotal</div>
                    <div style={{ fontFamily: font.mono, fontSize: 18, marginTop: 6 }}>
                      ${priced.subtotal.toFixed(2)}
                    </div>
                  </div>

                  <div
                    style={{
                      padding: 12,
                      borderRadius: radius.md,
                      border: `1px solid ${C.divider}`,
                      background: "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
                    }}
                  >
                    <div style={{ fontFamily: font.display, fontWeight: 800, color: C.navy }}>Profit (Markup)</div>
                    <div style={{ fontFamily: font.mono, fontSize: 18, marginTop: 6 }}>
                      ${priced.profit.toFixed(2)}
                    </div>
                    <div style={{ marginTop: 6, fontSize: 12, color: C.muted, fontFamily: font.mono }}>
                      Markup: {markupPct}%
                    </div>
                  </div>

                  <div
                    style={{
                      gridColumn: "1 / -1",
                      padding: 14,
                      borderRadius: radius.md,
                      border: `1px solid rgba(0,119,139,0.22)`,
                      background: `linear-gradient(135deg, ${C.tealLight} 0%, #F6FBFC 60%, ${C.goldLight} 100%)`,
                    }}
                  >
                    <div style={{ fontFamily: font.display, fontWeight: 900, color: C.navy }}>
                      Final Price to Customer
                    </div>
                    <div style={{ fontFamily: font.mono, fontSize: 26, marginTop: 8, color: C.ink }}>
                      ${priced.finalTotal.toFixed(2)}
                    </div>

                    <div style={{ marginTop: 8, fontSize: 12, color: C.muted, fontFamily: font.mono }}>
                      Applied: {priced.applied.state} · Mx {priced.applied.materialMultiplier} · Lx{" "}
                      {priced.applied.laborMultiplier}
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}