"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";

import { getProjects } from "../../../../lib/projectStore";
import { priceEstimate, type MaterialLine } from "../../../../lib/pricing/priceEngine";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Draft = {
  savedAt: string;
  jobDescription?: string;
  estimate?: GeneratedEstimate;
  laborRate?: number;
  markupPct?: number;
  permitFee?: number;
};

type UIState = { isSaved: boolean; lastSavedAt?: string };

type GeneratedEstimate = {
  generatedAt: string;
  summary: string;
  assumptions: string[];
  materials: MaterialLine[];
  laborHours: number;
};

function uid() {
  return Math.random().toString(36).slice(2, 10);
}

function shortScope(text: string, max = 140) {
  if (!text) return "";
  const cleaned = text.replace(/generated by ai.*$/i, "").replace(/ai[- ]?generated.*$/i, "").replace(/\s+/g, " ").trim();
  if (cleaned.length <= max) return cleaned;
  return cleaned.slice(0, max).replace(/\s+\S*$/, "") + "...";
}

function autoTitle(scope: string) {
  const s = scope.toLowerCase();
  if (s.includes("water heater")) return "Water Heater Circuit";
  if (s.includes("ev") || s.includes("charger")) return "EV Charger Installation";
  if (s.includes("panel") || s.includes("service")) return "Electrical Panel Work";
  if (s.includes("receptacle") || s.includes("outlet")) return "Outlet Installation";
  if (s.includes("light") || s.includes("fixture")) return "Lighting Installation";
  if (s.includes("generator")) return "Generator Electrical Work";
  return "Electrical Scope of Work";
}

// ---------------------------------------------------------------------------
// Design tokens
// ---------------------------------------------------------------------------

const C = {
  teal: "#00778B", tealDark: "#005F70", tealLight: "#E0F4F7",
  gold: "#C8A96E", goldLight: "#F5ECD8",
  navy: "#003057", navyMid: "#04406B",
  white: "#FFFFFF", offWhite: "#F7FAFC",
  ink: "#0A1F33", muted: "rgba(0,48,87,0.52)",
  divider: "rgba(0,119,139,0.14)",
  warn: "rgba(200,169,110,0.18)",
} as const;

const shadows = {
  card:  "0 4px 24px rgba(0,48,87,0.09), 0 1px 4px rgba(0,48,87,0.06)",
  raised:"0 8px 32px rgba(0,48,87,0.12), 0 2px 8px rgba(0,48,87,0.07)",
  teal:  "0 4px 20px rgba(0,119,139,0.22)",
} as const;

const radius = { sm: 10, md: 14, lg: 18 } as const;

const font = {
  display: "'Barlow Condensed', 'Arial Narrow', Arial, sans-serif",
  body:    "'DM Sans', 'Segoe UI', system-ui, sans-serif",
  mono:    "'DM Mono', 'Fira Code', monospace",
} as const;

// ---------------------------------------------------------------------------
// Shared styles
// ---------------------------------------------------------------------------

const panelStyle: CSSProperties = {
  background: C.white, border: `1px solid ${C.divider}`,
  borderRadius: radius.lg, boxShadow: shadows.card,
  padding: 18, fontFamily: font.body,
};

const btnPrimary: CSSProperties = {
  padding: "10px 20px", borderRadius: radius.sm,
  border: `1.5px solid ${C.tealDark}`,
  background: `linear-gradient(160deg, ${C.teal} 0%, ${C.tealDark} 100%)`,
  color: C.white, fontFamily: font.display, fontWeight: 700,
  fontSize: 14, letterSpacing: 0.6, cursor: "pointer",
  boxShadow: shadows.teal, whiteSpace: "nowrap",
};

const btnSecondary: CSSProperties = {
  padding: "9px 14px", borderRadius: radius.sm,
  border: `1px solid rgba(0,119,139,0.26)`,
  background: `linear-gradient(180deg, ${C.white} 0%, #F6FBFC 100%)`,
  color: C.navy, fontFamily: font.display, fontWeight: 800,
  fontSize: 13, letterSpacing: 0.55, cursor: "pointer",
  boxShadow: "0 6px 18px rgba(0,48,87,0.08)", whiteSpace: "nowrap",
};

const inputStyle: CSSProperties = {
  width: "100%", padding: "12px 12px", borderRadius: radius.md,
  border: `1px solid rgba(0,119,139,0.22)`, outline: "none",
  fontFamily: font.body, fontSize: 14, lineHeight: 1.4,
  color: C.ink, background: "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
};

const miniInput: CSSProperties = {
  width: 110, padding: "8px 10px", borderRadius: radius.md,
  border: `1px solid rgba(0,119,139,0.22)`, outline: "none",
  fontFamily: font.mono, fontSize: 13, color: C.ink,
  background: "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
};

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function NewEstimatePage() {
  const params    = useParams<{ id: string }>();
  const projectId = params?.id;
  const project   = getProjects().find((p) => p.id === projectId);
  const draftKey  = `voltscope:draft-estimate:${projectId ?? "unknown"}`;

  const [uiState,        setUiState]        = useState<UIState>({ isSaved: false });
  const [jobDescription, setJobDescription] = useState("");
  const [estimate,       setEstimate]       = useState<GeneratedEstimate | null>(null);
  const [markupPct,      setMarkupPct]      = useState(20);
  const [laborRate,      setLaborRate]      = useState(150);
  const [permitFee,      setPermitFee]      = useState(100);
  const [showAll,        setShowAll]        = useState(false);
  const [genState, setGenState] = useState<{ status: "idle"|"loading"|"ready"|"error"; msg?: string }>({ status: "idle" });
  const [progress, setProgress] = useState(0);

  // Restore draft
  useEffect(() => {
    if (!projectId) return;
    const raw = localStorage.getItem(draftKey);
    if (!raw) return;
    try {
      const saved = JSON.parse(raw) as Partial<Draft>;
      if (typeof saved.jobDescription === "string") setJobDescription(saved.jobDescription);
      if (typeof saved.laborRate === "number")       setLaborRate(saved.laborRate);
      if (typeof saved.markupPct === "number")       setMarkupPct(saved.markupPct);
      if (typeof saved.permitFee === "number")       setPermitFee(saved.permitFee);
      if (saved.estimate) { setEstimate(saved.estimate); setGenState({ status: "ready" }); }
      if (saved.savedAt)  setUiState({ isSaved: true, lastSavedAt: saved.savedAt });
    } catch { /* ignore */ }
  }, [projectId, draftKey]);

  // Progress bar
  useEffect(() => {
    if (genState.status !== "loading") { setProgress(0); return; }
    setProgress(8);
    const id = window.setInterval(() => setProgress((p) => Math.min(92, p + Math.max(1, Math.round((92 - p) * 0.12)))), 250);
    return () => window.clearInterval(id);
  }, [genState.status]);

  // Compute pricing from estimate materials
  const priced = useMemo(() => {
    if (!estimate) return null;
    const base = priceEstimate({
      month:      new Date().toISOString().slice(0, 7),
      state:      "NC",
      laborRate,
      markupPct,
      laborHours: estimate.laborHours,
      materials:  estimate.materials,
    });
    return {
      ...base,
      subtotal:   base.subtotal   + permitFee,
      finalTotal: base.finalTotal + permitFee,
    };
  }, [estimate, laborRate, markupPct, permitFee]);

  function saveDraft() {
    if (!projectId) return;
    const payload: Draft = {
      savedAt:        new Date().toISOString(),
      jobDescription: jobDescription.trim(),
      estimate:       estimate ?? undefined,
      laborRate, markupPct, permitFee,
    };
    localStorage.setItem(draftKey, JSON.stringify(payload));
    setUiState({ isSaved: true, lastSavedAt: payload.savedAt });
  }

  async function handleGenerate() {
    const text = jobDescription.trim();
    if (!text) { setGenState({ status: "error", msg: "Please enter a job description first." }); return; }

    setGenState({ status: "loading" });

    const controller = new AbortController();
    const timeoutId  = window.setTimeout(() => controller.abort(), 30_000);

    try {
      const r   = await fetch("/api/estimate", {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ description: text, laborRate, markupPct }),
        signal:  controller.signal,
      });

      const data = await r.json().catch(() => null);

      if (!r.ok || !data) {
        setGenState({ status: "error", msg: data?.error ?? "API error — please try again." });
        return;
      }

      const generated: GeneratedEstimate = {
        generatedAt: new Date().toISOString(),
        summary:     data.summary     ?? "Scope generated from job description.",
        assumptions: Array.isArray(data.assumptions) ? data.assumptions : [],
        materials:   Array.isArray(data.materials)   ? data.materials   : [],
        laborHours:  typeof data.laborHours === "number" && data.laborHours > 0 ? data.laborHours : 2,
      };

      setEstimate(generated);
      setProgress(100);
      setGenState({ status: "ready" });
      setShowAll(false);

      if (projectId) {
        const payload: Draft = { savedAt: new Date().toISOString(), jobDescription: text, estimate: generated, laborRate, markupPct, permitFee };
        localStorage.setItem(draftKey, JSON.stringify(payload));
        setUiState({ isSaved: true, lastSavedAt: payload.savedAt });
      }
    } catch (e: unknown) {
      const isTimeout = e instanceof Error && e.name === "AbortError";
      setGenState({ status: "error", msg: isTimeout ? "Request timed out — please try again." : "Request failed — please try again." });
    } finally {
      window.clearTimeout(timeoutId);
    }
  }

  function clearEstimate() {
    setJobDescription(""); setEstimate(null); setProgress(0);
    setPermitFee(100); setGenState({ status: "idle" }); setShowAll(false);
    if (projectId) { localStorage.removeItem(draftKey); setUiState({ isSaved: false }); }
  }

  const canGenerate = useMemo(
    () => jobDescription.trim().length > 0 && genState.status !== "loading" && genState.status !== "ready",
    [jobDescription, genState.status]
  );

  const materialRows   = priced?.pricedMaterials ?? [];
  const PREVIEW        = 5;
  const visibleRows    = showAll ? materialRows : materialRows.slice(0, PREVIEW);
  const hiddenCount    = Math.max(0, materialRows.length - PREVIEW);

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700;800&family=DM+Sans:wght@400;500;600;700&family=DM+Mono:wght@400;500&display=swap');
        * { box-sizing: border-box; }
        body { margin: 0; background: ${C.offWhite}; }
        .page {
          min-height: 100vh;
          background: linear-gradient(160deg, #EAF4F7 0%, #F7FAFC 40%, #F0EBE1 100%);
          padding: 20px; font-family: ${font.body}; color: ${C.ink};
        }
        .content  { max-width: 960px; margin: 0 auto; }
        .grid     { display: grid; gap: 14px; margin-top: 14px; }
        .header-bar {
          display: flex; align-items: center; justify-content: space-between;
          gap: 14px; padding: 14px 20px; border-radius: ${radius.lg}px;
          background: linear-gradient(135deg, ${C.navy} 0%, ${C.navyMid} 100%);
          box-shadow: ${shadows.raised}; flex-wrap: wrap;
        }
        .header-left { display: flex; align-items: center; gap: 12px; }
        .header-accent { width: 4px; height: 38px; border-radius: 4px; background: linear-gradient(180deg, ${C.gold} 0%, ${C.teal} 100%); flex-shrink: 0; }
        .back-link {
          display: inline-flex; align-items: center; gap: 6px; text-decoration: none;
          color: rgba(255,255,255,0.75); font-weight: 600; font-size: 13px;
          padding: 7px 12px; border-radius: ${radius.sm}px;
          border: 1px solid rgba(255,255,255,0.15); background: rgba(255,255,255,0.08);
        }
        .back-link:hover { background: rgba(255,255,255,0.16); color: ${C.white}; }
        .panel-title { font-family: ${font.display}; font-weight: 800; font-size: 16px; color: ${C.navy}; margin: 0; }
        .badge {
          display: inline-block; padding: 2px 9px; border-radius: 20px;
          font-family: ${font.display}; font-weight: 700; font-size: 11px;
          letter-spacing: 0.8px; text-transform: uppercase;
          background: ${C.tealLight}; color: ${C.tealDark}; border: 1px solid rgba(0,119,139,0.20);
        }
        .row-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 12px; gap: 12px; flex-wrap: wrap; }
      `}</style>

      <div className="page">
        <div className="content">

          {/* ── Header ── */}
          <div className="header-bar">
            <div className="header-left">
              <div className="header-accent" />
              <Link href={`/projects/${projectId}`} className="back-link">← Back</Link>
              <div>
                <div style={{ fontFamily: font.display, fontWeight: 800, fontSize: 22, color: C.white }}>New Estimate</div>
                <div style={{ fontSize: 13, color: "rgba(255,255,255,0.55)", marginTop: 2 }}>
                  {project?.customerName ?? "Unnamed Project"} · {project?.jobType ?? "Unknown"}
                </div>
                {uiState.isSaved && uiState.lastSavedAt && (
                  <div style={{ fontSize: 11, color: "rgba(255,255,255,0.45)", marginTop: 3, fontFamily: font.mono }}>
                    Last saved: {new Date(uiState.lastSavedAt).toLocaleString()}
                  </div>
                )}
              </div>
            </div>
            <button type="button" onClick={saveDraft} style={btnPrimary}>💾 Save Draft</button>
          </div>

          <div className="grid">

            {/* ── Job Description ── */}
            <div style={panelStyle}>
              <div className="row-header">
                <h2 className="panel-title">Job Description</h2>
                <span className="badge">Input</span>
              </div>

              <textarea
                value={jobDescription}
                onChange={(e) => { setJobDescription(e.target.value); if (genState.status === "error") setGenState({ status: "idle" }); }}
                placeholder="Describe the job scope… e.g. Install EV charger in garage, 25ft run through attic, new 60A breaker, NEMA 14-50 outlet."
                rows={5}
                style={inputStyle}
              />

              <div style={{ display: "flex", gap: 10, alignItems: "center", marginTop: 12, flexWrap: "wrap" }}>
                <button
                  type="button" onClick={handleGenerate}
                  style={{ ...btnSecondary, opacity: canGenerate ? 1 : 0.5, cursor: canGenerate ? "pointer" : "not-allowed" }}
                  disabled={!canGenerate}
                >
                  ⚡ Generate Estimate
                </button>

                <button
                  type="button" onClick={clearEstimate}
                  style={{ ...btnSecondary, opacity: genState.status === "ready" ? 1 : 0.5, cursor: genState.status === "ready" ? "pointer" : "not-allowed" }}
                  disabled={genState.status !== "ready"}
                >
                  🧹 Start New
                </button>

                {genState.status === "loading" && (
                  <>
                    <span style={{ fontFamily: font.mono, fontSize: 12, color: C.teal, background: C.tealLight, padding: "5px 10px", borderRadius: 999, border: `1px solid rgba(0,119,139,0.18)` }}>
                      Generating…
                    </span>
                    <div style={{ width: "100%", maxWidth: 380, height: 8, borderRadius: 999, overflow: "hidden", background: "rgba(0,48,87,0.06)", border: `1px solid rgba(0,119,139,0.18)` }}>
                      <div style={{ height: "100%", width: `${progress}%`, background: `linear-gradient(90deg, ${C.teal}, ${C.tealDark})`, transition: "width 180ms ease" }} />
                    </div>
                  </>
                )}

                {genState.status === "error" && (
                  <span style={{ fontFamily: font.mono, fontSize: 12, color: "#a01818", background: "rgba(255,235,235,0.9)", padding: "5px 10px", borderRadius: 999, border: "1px solid rgba(160,24,24,0.18)" }}>
                    {genState.msg}
                  </span>
                )}

                {genState.status === "ready" && estimate?.generatedAt && (
                  <span style={{ fontFamily: font.mono, fontSize: 12, color: C.muted, background: "rgba(0,48,87,0.06)", padding: "5px 10px", borderRadius: 999 }}>
                    Generated: {new Date(estimate.generatedAt).toLocaleString()}
                  </span>
                )}
              </div>

              <div style={{ marginTop: 8, fontSize: 12, color: C.muted }}>
                Tip: Include distances, voltage/amps, number of devices, and access details (attic, crawlspace, finished walls, etc).
              </div>
            </div>

            {/* ── Scope Summary ── */}
            {estimate && (
              <div style={{ ...panelStyle, padding: 0, overflow: "hidden" }}>
                <div style={{ padding: "14px 18px", background: `linear-gradient(135deg, ${C.tealLight} 0%, #F8FCFD 100%)`, borderBottom: `1px solid ${C.divider}` }}>
                  <div className="row-header" style={{ marginBottom: 0 }}>
                    <h2 className="panel-title">Scope Summary</h2>
                    <span className="badge">Draft</span>
                  </div>
                </div>
                <div style={{ padding: 18 }}>
                  <div style={{ fontFamily: font.display, fontSize: 20, fontWeight: 800, color: C.navy, marginBottom: 6 }}>
                    {autoTitle(estimate.summary)}
                  </div>
                  <div style={{ fontSize: 14, lineHeight: 1.55, color: C.ink }}>{shortScope(estimate.summary)}</div>
                  {estimate.assumptions.length > 0 && (
                    <div style={{ marginTop: 10, fontSize: 12, color: C.muted, lineHeight: 1.5 }}>
                      {estimate.assumptions.join(" · ")}
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* ── Pricing Controls ── */}
            {estimate && (
              <div style={panelStyle}>
                <div className="row-header">
                  <h2 className="panel-title">Pricing Settings</h2>
                  <span className="badge">Adjustable</span>
                </div>
                <div style={{ display: "flex", gap: 16, flexWrap: "wrap", alignItems: "center" }}>
                  {[
                    { label: "Labor Rate", value: laborRate, set: setLaborRate, suffix: "/hr" },
                    { label: "Markup",     value: markupPct, set: setMarkupPct, suffix: "%" },
                    { label: "Permit Fee", value: permitFee, set: setPermitFee, suffix: "$" },
                  ].map(({ label, value, set, suffix }) => (
                    <div key={label} style={{ display: "flex", gap: 8, alignItems: "center" }}>
                      <span style={{ fontFamily: font.display, fontWeight: 800, color: C.navy, fontSize: 14 }}>{label}</span>
                      <input
                        style={miniInput} inputMode="numeric" value={value}
                        onChange={(e) => { const v = Number(e.target.value); set(Number.isFinite(v) ? v : 0); }}
                        onBlur={saveDraft}
                      />
                      <span style={{ fontFamily: font.mono, color: C.muted, fontSize: 12 }}>{suffix}</span>
                    </div>
                  ))}
                  <button type="button" onClick={saveDraft} style={{ ...btnSecondary, marginLeft: "auto" }}>💾 Save</button>
                </div>
              </div>
            )}

            {/* ── Priced Material List ── */}
            {priced && materialRows.length > 0 && (
              <div style={{ ...panelStyle, padding: 0, overflow: "hidden" }}>
                <div style={{ padding: "14px 18px", background: `linear-gradient(135deg, ${C.tealLight} 0%, #F8FCFD 100%)`, borderBottom: `1px solid ${C.divider}` }}>
                  <div className="row-header" style={{ marginBottom: 0 }}>
                    <div>
                      <h2 className="panel-title">Material List</h2>
                      <div style={{ marginTop: 3, fontSize: 12, color: C.muted, fontFamily: font.mono }}>
                        {materialRows.length} items · ${priced.materialTotal.toFixed(2)}
                      </div>
                    </div>
                    <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                      <span className="badge">Priced</span>
                      {materialRows.length > PREVIEW && (
                        <button type="button" onClick={() => setShowAll((s) => !s)} style={{ ...btnSecondary, padding: "5px 10px", fontSize: 12 }}>
                          {showAll ? "Show Less" : `Show All (${materialRows.length})`}
                        </button>
                      )}
                    </div>
                  </div>
                </div>

                {/* Column headers */}
                <div style={{ display: "grid", gridTemplateColumns: "2fr 0.4fr 0.9fr 0.7fr", padding: "8px 16px", background: "rgba(0,48,87,0.04)", borderBottom: `1px solid ${C.divider}`, gap: 10 }}>
                  {["Item", "Qty", "Unit / Rate", "Total"].map((h, i) => (
                    <div key={h} style={{ fontFamily: font.display, fontWeight: 800, fontSize: 11, letterSpacing: 0.8, textTransform: "uppercase", color: C.muted, textAlign: i > 0 ? "right" : "left" }}>
                      {h}
                    </div>
                  ))}
                </div>

                {/* Material rows */}
                {visibleRows.map((m) => (
                  <div
                    key={m.skuKey}
                    style={{
                      display: "grid", gridTemplateColumns: "2fr 0.4fr 0.9fr 0.7fr",
                      padding: "12px 16px", borderBottom: `1px solid ${C.divider}`,
                      alignItems: "center", gap: 10,
                      background: m.missingFromPricebook
                        ? `linear-gradient(180deg, ${C.warn} 0%, rgba(245,236,216,0.4) 100%)`
                        : "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)",
                    }}
                  >
                    <div>
                      <div style={{ fontWeight: 700, color: C.navy, fontSize: 14, lineHeight: 1.25 }}>{m.name}</div>
                      <div style={{ marginTop: 3, fontSize: 11, color: C.muted, fontFamily: font.mono }}>
                        {m.skuKey}{m.missingFromPricebook ? " · ⚠ not in pricebook" : ""}
                      </div>
                    </div>
                    <div style={{ textAlign: "right", fontFamily: font.mono, color: C.ink, fontSize: 13 }}>{m.qty}</div>
                    <div style={{ textAlign: "right", fontFamily: font.mono, color: C.muted, fontSize: 13 }}>
                      {m.unit} @ ${m.adjUnitCost.toFixed(2)}
                    </div>
                    <div style={{ textAlign: "right", fontFamily: font.mono, color: C.ink, fontSize: 13, fontWeight: 600 }}>
                      ${m.lineTotal.toFixed(2)}
                    </div>
                  </div>
                ))}

                {!showAll && hiddenCount > 0 && (
                  <div style={{ padding: "10px 16px", background: "rgba(0,119,139,0.04)", fontSize: 12, color: C.muted, borderTop: `1px solid ${C.divider}` }}>
                    Showing {visibleRows.length} of {materialRows.length} items · {hiddenCount} more hidden
                  </div>
                )}
              </div>
            )}

            {/* ── Totals ── */}
            {priced && (
              <div style={panelStyle}>
                <div className="row-header">
                  <h2 className="panel-title">Totals</h2>
                  <span className="badge">Summary</span>
                </div>

                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                  {[
                    { label: "Material Total", value: priced.materialTotal, sub: `${materialRows.length} line items` },
                    { label: "Labor Total",    value: priced.laborTotal,    sub: `${estimate?.laborHours ?? 0} hrs @ $${laborRate}/hr` },
                    { label: "Subtotal",       value: priced.subtotal,      sub: `Includes permit $${permitFee.toFixed(2)}` },
                    { label: "Profit (Markup)",value: priced.profit,        sub: `${markupPct}% markup` },
                  ].map(({ label, value, sub }) => (
                    <div key={label} style={{ padding: 14, borderRadius: radius.md, border: `1px solid ${C.divider}`, background: "linear-gradient(180deg, #FFFFFF 0%, #FBFEFF 100%)" }}>
                      <div style={{ fontFamily: font.display, fontWeight: 800, color: C.navy, fontSize: 13 }}>{label}</div>
                      <div style={{ fontFamily: font.mono, fontSize: 20, marginTop: 6, color: C.ink }}>${value.toFixed(2)}</div>
                      <div style={{ marginTop: 4, fontSize: 11, color: C.muted, fontFamily: font.mono }}>{sub}</div>
                    </div>
                  ))}

                  {/* Final total */}
                  <div style={{ gridColumn: "1 / -1", padding: 16, borderRadius: radius.md, border: `1px solid rgba(0,119,139,0.22)`, background: `linear-gradient(135deg, ${C.tealLight} 0%, #F6FBFC 60%, ${C.goldLight} 100%)` }}>
                    <div style={{ fontFamily: font.display, fontWeight: 900, color: C.navy, fontSize: 14, letterSpacing: 0.4 }}>
                      Final Price to Customer
                    </div>
                    <div style={{ fontFamily: font.mono, fontSize: 32, marginTop: 8, color: C.ink, fontWeight: 600 }}>
                      ${priced.finalTotal.toFixed(2)}
                    </div>
                    <div style={{ marginTop: 8, fontSize: 12, color: C.muted, fontFamily: font.mono }}>
                      {priced.applied.state} · Material ×{priced.applied.materialMultiplier} · Labor ×{priced.applied.laborMultiplier}
                    </div>
                  </div>
                </div>
              </div>
            )}

          </div>
        </div>
      </div>
    </>
  );
}